go:
    version: 1.21.6
repository:
    path: github.com/thanos-io/thanosbench
build:
    binaries:
        - name: thanosbench
          path: ./cmd/thanosbench
    flags: -a -tags netgo
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
crossbuild:
    platforms:
        - linux/amd64
        - darwin/amd64
        - darwin/arm64
        - linux/arm64
        - windows/amd64
